spring.application.name=EzCloudShare

server.port=8084

spring.data.mongodb.uri=mongodb+srv://adityakumarhzb01_db_user:adityadev123@cluster0.t4hzqyx.mongodb.net/EzCloudShareDB


server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://engaged-reindeer-85.clerk.accounts.dev
clerk.jwks-url=https://engaged-reindeer-85.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_vxjnC5F/X52UGwGDHTf87Q8kSeXcfXUY


#file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB 


razorpay.key.id=rzp_test_SlYomEmBVaOxIR
razorpay.key.secret=k1gk3kpQCxUqESIocdlMC4ET

logging.level.root=INFO